Update javadoc for webauthn config
FroMage/quarkus pull request #1
Opened 2022-03-15 12:59 UTC by pmlopes

Signed-off-by: Paulo Lopes <pmlopes@gmail.com>

2022-03-15 13:02 UTC, pmlopes commented
@FroMage I've documented the options. I also noticed a small "smell". origin and domain, should not be allowed as requires used to double configure.

If from quarkus you can extract the protocol and listening port, you can rebuild the origin from the domain.

```
origin = protocol + "://" + domain + ":" + port
```

If you cannot do that you can extract the domain from the origin:

```
origin = "https://${domain}:port"
```

2022-03-15 13:17 UTC, FroMage requested changes

2022-03-15 13:17 UTC, FroMage commented on extensions/security-webauthn/runtime/src/main/java/io/quarkus/security/webauthn/WebAuthnRunTimeConfig.java
> +     * If your are calling WebAuthn API while your use is located at {@code https://example.com/login},
`your use`?

2022-03-15 13:17 UTC, FroMage commented on extensions/security-webauthn/runtime/src/main/java/io/quarkus/security/webauthn/WebAuthnRunTimeConfig.java
> +     * user is present during the authentication cerimonies, but in some cases, applications may want to reduce the
```suggestion
     * user is present during the authentication ceremonies, but in some cases, applications may want to reduce the
```

2022-03-15 13:17 UTC, FroMage commented on extensions/security-webauthn/runtime/src/main/java/io/quarkus/security/webauthn/WebAuthnRunTimeConfig.java
> +     * Non negative User Verification timeout. Authentication must occur within the timeout, this will prevent the user browser to be
```suggestion
     * Non negative User Verification timeout. Authentication must occur within the timeout, this will prevent the user browser from being
```

2022-03-15 13:17 UTC, FroMage commented on extensions/security-webauthn/runtime/src/main/java/io/quarkus/security/webauthn/WebAuthnRunTimeConfig.java
> +     * blocked with a pop-up required user verification, and the whole cerimony must be completed within the timeout
```suggestion
     * blocked with a pop-up required user verification, and the whole ceremony must be completed within the timeout
```

2022-03-15 13:17 UTC, FroMage commented on extensions/security-webauthn/runtime/src/main/java/io/quarkus/security/webauthn/WebAuthnRunTimeConfig.java
> +     * configuration on user behalf.
```suggestion
     * configuration on the user's behalf.
```

2022-03-15 13:18 UTC, FroMage commented
> If from quarkus you can extract the protocol and listening port, you can rebuild the origin from the domain.

Ah, OK, I'll pick one of the two then

2022-03-16 09:43 UTC, FroMage approved these changes

2022-03-16 09:44 UTC, merged